---
prometheus_image: 'prom/prometheus'
prometheus_image_version: 'latest'
prometheus_port: '9090'
haproxy_exporter_port: '9101'
bind_exporter_port: '9119'
ssl_exporter_port: '9219'
openstack_exporter_port: '9180'

provision_state: "started"
